// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMS.infra.Persistence.Context;

#nullable disable

namespace tms.infra.Migrations
{
    [DbContext(typeof(dbContext))]
    [Migration("20250221051025_addEventLog")]
    partial class addEventLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("TMS.domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date_Created")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date_Created = "2025-02-21T05:10:24.4929333+00:00",
                            Name = "Vancouver",
                            TimeZone = "Pacific Standard Time"
                        },
                        new
                        {
                            Id = 2,
                            Date_Created = "2025-02-21T05:10:24.4929424+00:00",
                            Name = "Victoria",
                            TimeZone = "Pacific Standard Time"
                        },
                        new
                        {
                            Id = 3,
                            Date_Created = "2025-02-21T05:10:24.4929445+00:00",
                            Name = "Kelowna",
                            TimeZone = "Pacific Standard Time"
                        },
                        new
                        {
                            Id = 4,
                            Date_Created = "2025-02-21T05:10:24.4929463+00:00",
                            Name = "Kamloops",
                            TimeZone = "Pacific Standard Time"
                        },
                        new
                        {
                            Id = 5,
                            Date_Created = "2025-02-21T05:10:24.4929482+00:00",
                            Name = "Prince George",
                            TimeZone = "Pacific Standard Time"
                        },
                        new
                        {
                            Id = 6,
                            Date_Created = "2025-02-21T05:10:24.4929502+00:00",
                            Name = "Calgary",
                            TimeZone = "Mountain Standard Time"
                        },
                        new
                        {
                            Id = 7,
                            Date_Created = "2025-02-21T05:10:24.4929519+00:00",
                            Name = "Edmonton",
                            TimeZone = "Mountain Standard Time"
                        },
                        new
                        {
                            Id = 8,
                            Date_Created = "2025-02-21T05:10:24.4929538+00:00",
                            Name = "Lethbridge",
                            TimeZone = "Mountain Standard Time"
                        },
                        new
                        {
                            Id = 9,
                            Date_Created = "2025-02-21T05:10:24.4929556+00:00",
                            Name = "Red Deer",
                            TimeZone = "Mountain Standard Time"
                        },
                        new
                        {
                            Id = 10,
                            Date_Created = "2025-02-21T05:10:24.4929577+00:00",
                            Name = "Fort McMurray",
                            TimeZone = "Mountain Standard Time"
                        },
                        new
                        {
                            Id = 11,
                            Date_Created = "2025-02-21T05:10:24.4929598+00:00",
                            Name = "Regina",
                            TimeZone = "Canada Central Standard Time"
                        },
                        new
                        {
                            Id = 12,
                            Date_Created = "2025-02-21T05:10:24.4929618+00:00",
                            Name = "Saskatoon",
                            TimeZone = "Canada Central Standard Time"
                        },
                        new
                        {
                            Id = 13,
                            Date_Created = "2025-02-21T05:10:24.4929638+00:00",
                            Name = "Moose Jaw",
                            TimeZone = "Canada Central Standard Time"
                        },
                        new
                        {
                            Id = 14,
                            Date_Created = "2025-02-21T05:10:24.4929724+00:00",
                            Name = "Brandon",
                            TimeZone = "Central Standard Time"
                        },
                        new
                        {
                            Id = 15,
                            Date_Created = "2025-02-21T05:10:24.4929743+00:00",
                            Name = "Winnipeg",
                            TimeZone = "Central Standard Time"
                        },
                        new
                        {
                            Id = 16,
                            Date_Created = "2025-02-21T05:10:24.4929762+00:00",
                            Name = "Thunder Bay",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 17,
                            Date_Created = "2025-02-21T05:10:24.4929782+00:00",
                            Name = "Sault Ste. Marie",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 18,
                            Date_Created = "2025-02-21T05:10:24.4929800+00:00",
                            Name = "Sudbury",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 19,
                            Date_Created = "2025-02-21T05:10:24.4929817+00:00",
                            Name = "North Bay",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 20,
                            Date_Created = "2025-02-21T05:10:24.4929834+00:00",
                            Name = "Barrie",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 21,
                            Date_Created = "2025-02-21T05:10:24.4929851+00:00",
                            Name = "Toronto",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 22,
                            Date_Created = "2025-02-21T05:10:24.4929869+00:00",
                            Name = "Mississauga",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 23,
                            Date_Created = "2025-02-21T05:10:24.4929886+00:00",
                            Name = "Hamilton",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 24,
                            Date_Created = "2025-02-21T05:10:24.4929903+00:00",
                            Name = "London",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 25,
                            Date_Created = "2025-02-21T05:10:24.4929921+00:00",
                            Name = "Kitchener",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 26,
                            Date_Created = "2025-02-21T05:10:24.4929937+00:00",
                            Name = "Windsor",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 27,
                            Date_Created = "2025-02-21T05:10:24.4929956+00:00",
                            Name = "St. Catharines",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 28,
                            Date_Created = "2025-02-21T05:10:24.4929973+00:00",
                            Name = "Oshawa",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 29,
                            Date_Created = "2025-02-21T05:10:24.4929989+00:00",
                            Name = "Kingston",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 30,
                            Date_Created = "2025-02-21T05:10:24.4930007+00:00",
                            Name = "Ottawa",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 31,
                            Date_Created = "2025-02-21T05:10:24.4930024+00:00",
                            Name = "Gatineau",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 32,
                            Date_Created = "2025-02-21T05:10:24.4930041+00:00",
                            Name = "Montreal",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 33,
                            Date_Created = "2025-02-21T05:10:24.4930058+00:00",
                            Name = "Quebec City",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 34,
                            Date_Created = "2025-02-21T05:10:24.4930081+00:00",
                            Name = "Sherbrooke",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 35,
                            Date_Created = "2025-02-21T05:10:24.4930101+00:00",
                            Name = "Trois-Rivières",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 36,
                            Date_Created = "2025-02-21T05:10:24.4930118+00:00",
                            Name = "Saguenay",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 37,
                            Date_Created = "2025-02-21T05:10:24.4930136+00:00",
                            Name = "Rimouski",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 38,
                            Date_Created = "2025-02-21T05:10:24.4930153+00:00",
                            Name = "Edmundston",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 39,
                            Date_Created = "2025-02-21T05:10:24.4930172+00:00",
                            Name = "Fredericton",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 40,
                            Date_Created = "2025-02-21T05:10:24.4930190+00:00",
                            Name = "Moncton",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 41,
                            Date_Created = "2025-02-21T05:10:24.4930208+00:00",
                            Name = "Saint John",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 42,
                            Date_Created = "2025-02-21T05:10:24.4930225+00:00",
                            Name = "Bathurst",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 43,
                            Date_Created = "2025-02-21T05:10:24.4930325+00:00",
                            Name = "Charlottetown",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 44,
                            Date_Created = "2025-02-21T05:10:24.4930345+00:00",
                            Name = "Summerside",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 45,
                            Date_Created = "2025-02-21T05:10:24.4930362+00:00",
                            Name = "Sydney",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 46,
                            Date_Created = "2025-02-21T05:10:24.4930380+00:00",
                            Name = "Truro",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 47,
                            Date_Created = "2025-02-21T05:10:24.4930399+00:00",
                            Name = "New Glasgow",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 48,
                            Date_Created = "2025-02-21T05:10:24.4930416+00:00",
                            Name = "Dartmouth",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 49,
                            Date_Created = "2025-02-21T05:10:24.4930434+00:00",
                            Name = "Halifax",
                            TimeZone = "Atlantic Standard Time"
                        });
                });

            modelBuilder.Entity("TMS.domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Date_Created")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("EquipmentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TripId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("TripId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("TMS.domain.Entities.Event_Code", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<string>("Date_Created")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Event_Codes");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Code = "W",
                            Date_Created = "2025-02-21T05:10:24.4913558+00:00",
                            Description = "Railcar equipment is released from origin",
                            Name = "Released"
                        },
                        new
                        {
                            Id = -2,
                            Code = "A",
                            Date_Created = "2025-02-21T05:10:24.4913664+00:00",
                            Description = "Railcar equipment arrives at a city on route",
                            Name = "Arrived"
                        },
                        new
                        {
                            Id = -3,
                            Code = "D",
                            Date_Created = "2025-02-21T05:10:24.4913692+00:00",
                            Description = "Railcar equipment departs from a city on route",
                            Name = "Departed"
                        },
                        new
                        {
                            Id = -4,
                            Code = "Z",
                            Date_Created = "2025-02-21T05:10:24.4913714+00:00",
                            Description = "Railcar equipment is placed at destination",
                            Name = "Placed"
                        });
                });

            modelBuilder.Entity("TMS.domain.Entities.Trip", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Date_Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("Destination_CityId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Duration")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("CAST((julianday(End_Date || ' UTC') - julianday(Start_Date || ' UTC')) * 24 * 60 AS INTEGER)", true);

                    b.Property<DateTimeOffset>("End_Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("EquipmentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasIssue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Origin_CityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Start_Date")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Destination_CityId");

                    b.HasIndex("Origin_CityId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("TMS.domain.Entities.Event", b =>
                {
                    b.HasOne("TMS.domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TMS.domain.Entities.Trip", "Trip")
                        .WithMany("Events")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TMS.domain.Entities.Trip", b =>
                {
                    b.HasOne("TMS.domain.Entities.City", "Destination_City")
                        .WithMany("Destination_Cities")
                        .HasForeignKey("Destination_CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TMS.domain.Entities.City", "Origin_City")
                        .WithMany("Start_Cities")
                        .HasForeignKey("Origin_CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destination_City");

                    b.Navigation("Origin_City");
                });

            modelBuilder.Entity("TMS.domain.Entities.City", b =>
                {
                    b.Navigation("Destination_Cities");

                    b.Navigation("Start_Cities");
                });

            modelBuilder.Entity("TMS.domain.Entities.Trip", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
