// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMS.infra.Persistence.Context;

#nullable disable

namespace tms.infra.Migrations
{
    [DbContext(typeof(dbContext))]
    [Migration("20250221231052_updateDuration")]
    partial class updateDuration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("TMS.domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date_Created")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date_Created = "2025-02-21T23:10:51.3070845+00:00",
                            Name = "Vancouver",
                            TimeZone = "Pacific Standard Time"
                        },
                        new
                        {
                            Id = 2,
                            Date_Created = "2025-02-21T23:10:51.3071043+00:00",
                            Name = "Victoria",
                            TimeZone = "Pacific Standard Time"
                        },
                        new
                        {
                            Id = 3,
                            Date_Created = "2025-02-21T23:10:51.3071103+00:00",
                            Name = "Kelowna",
                            TimeZone = "Pacific Standard Time"
                        },
                        new
                        {
                            Id = 4,
                            Date_Created = "2025-02-21T23:10:51.3071148+00:00",
                            Name = "Kamloops",
                            TimeZone = "Pacific Standard Time"
                        },
                        new
                        {
                            Id = 5,
                            Date_Created = "2025-02-21T23:10:51.3071192+00:00",
                            Name = "Prince George",
                            TimeZone = "Pacific Standard Time"
                        },
                        new
                        {
                            Id = 6,
                            Date_Created = "2025-02-21T23:10:51.3071238+00:00",
                            Name = "Calgary",
                            TimeZone = "Mountain Standard Time"
                        },
                        new
                        {
                            Id = 7,
                            Date_Created = "2025-02-21T23:10:51.3071278+00:00",
                            Name = "Edmonton",
                            TimeZone = "Mountain Standard Time"
                        },
                        new
                        {
                            Id = 8,
                            Date_Created = "2025-02-21T23:10:51.3071323+00:00",
                            Name = "Lethbridge",
                            TimeZone = "Mountain Standard Time"
                        },
                        new
                        {
                            Id = 9,
                            Date_Created = "2025-02-21T23:10:51.3071366+00:00",
                            Name = "Red Deer",
                            TimeZone = "Mountain Standard Time"
                        },
                        new
                        {
                            Id = 10,
                            Date_Created = "2025-02-21T23:10:51.3071416+00:00",
                            Name = "Fort McMurray",
                            TimeZone = "Mountain Standard Time"
                        },
                        new
                        {
                            Id = 11,
                            Date_Created = "2025-02-21T23:10:51.3071463+00:00",
                            Name = "Regina",
                            TimeZone = "Canada Central Standard Time"
                        },
                        new
                        {
                            Id = 12,
                            Date_Created = "2025-02-21T23:10:51.3071510+00:00",
                            Name = "Saskatoon",
                            TimeZone = "Canada Central Standard Time"
                        },
                        new
                        {
                            Id = 13,
                            Date_Created = "2025-02-21T23:10:51.3071557+00:00",
                            Name = "Moose Jaw",
                            TimeZone = "Canada Central Standard Time"
                        },
                        new
                        {
                            Id = 14,
                            Date_Created = "2025-02-21T23:10:51.3071599+00:00",
                            Name = "Brandon",
                            TimeZone = "Central Standard Time"
                        },
                        new
                        {
                            Id = 15,
                            Date_Created = "2025-02-21T23:10:51.3071642+00:00",
                            Name = "Winnipeg",
                            TimeZone = "Central Standard Time"
                        },
                        new
                        {
                            Id = 16,
                            Date_Created = "2025-02-21T23:10:51.3071688+00:00",
                            Name = "Thunder Bay",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 17,
                            Date_Created = "2025-02-21T23:10:51.3071734+00:00",
                            Name = "Sault Ste. Marie",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 18,
                            Date_Created = "2025-02-21T23:10:51.3071808+00:00",
                            Name = "Sudbury",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 19,
                            Date_Created = "2025-02-21T23:10:51.3071852+00:00",
                            Name = "North Bay",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 20,
                            Date_Created = "2025-02-21T23:10:51.3071892+00:00",
                            Name = "Barrie",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 21,
                            Date_Created = "2025-02-21T23:10:51.3071933+00:00",
                            Name = "Toronto",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 22,
                            Date_Created = "2025-02-21T23:10:51.3071976+00:00",
                            Name = "Mississauga",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 23,
                            Date_Created = "2025-02-21T23:10:51.3072021+00:00",
                            Name = "Hamilton",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 24,
                            Date_Created = "2025-02-21T23:10:51.3072060+00:00",
                            Name = "London",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 25,
                            Date_Created = "2025-02-21T23:10:51.3072102+00:00",
                            Name = "Kitchener",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 26,
                            Date_Created = "2025-02-21T23:10:51.3072143+00:00",
                            Name = "Windsor",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 27,
                            Date_Created = "2025-02-21T23:10:51.3072185+00:00",
                            Name = "St. Catharines",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 28,
                            Date_Created = "2025-02-21T23:10:51.3072225+00:00",
                            Name = "Oshawa",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 29,
                            Date_Created = "2025-02-21T23:10:51.3072264+00:00",
                            Name = "Kingston",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 30,
                            Date_Created = "2025-02-21T23:10:51.3072302+00:00",
                            Name = "Ottawa",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 31,
                            Date_Created = "2025-02-21T23:10:51.3072344+00:00",
                            Name = "Gatineau",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 32,
                            Date_Created = "2025-02-21T23:10:51.3072382+00:00",
                            Name = "Montreal",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 33,
                            Date_Created = "2025-02-21T23:10:51.3072423+00:00",
                            Name = "Quebec City",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 34,
                            Date_Created = "2025-02-21T23:10:51.3072471+00:00",
                            Name = "Sherbrooke",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 35,
                            Date_Created = "2025-02-21T23:10:51.3072513+00:00",
                            Name = "Trois-Rivières",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 36,
                            Date_Created = "2025-02-21T23:10:51.3072558+00:00",
                            Name = "Saguenay",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 37,
                            Date_Created = "2025-02-21T23:10:51.3072602+00:00",
                            Name = "Rimouski",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 38,
                            Date_Created = "2025-02-21T23:10:51.3072667+00:00",
                            Name = "Edmundston",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 39,
                            Date_Created = "2025-02-21T23:10:51.3072711+00:00",
                            Name = "Fredericton",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 40,
                            Date_Created = "2025-02-21T23:10:51.3072750+00:00",
                            Name = "Moncton",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 41,
                            Date_Created = "2025-02-21T23:10:51.3072788+00:00",
                            Name = "Saint John",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 42,
                            Date_Created = "2025-02-21T23:10:51.3072832+00:00",
                            Name = "Bathurst",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 43,
                            Date_Created = "2025-02-21T23:10:51.3072882+00:00",
                            Name = "Charlottetown",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 44,
                            Date_Created = "2025-02-21T23:10:51.3072928+00:00",
                            Name = "Summerside",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 45,
                            Date_Created = "2025-02-21T23:10:51.3072971+00:00",
                            Name = "Sydney",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 46,
                            Date_Created = "2025-02-21T23:10:51.3073010+00:00",
                            Name = "Truro",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 47,
                            Date_Created = "2025-02-21T23:10:51.3073054+00:00",
                            Name = "New Glasgow",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 48,
                            Date_Created = "2025-02-21T23:10:51.3073093+00:00",
                            Name = "Dartmouth",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 49,
                            Date_Created = "2025-02-21T23:10:51.3073132+00:00",
                            Name = "Halifax",
                            TimeZone = "Atlantic Standard Time"
                        });
                });

            modelBuilder.Entity("TMS.domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Date_Created")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("EquipmentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TripId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("TripId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("TMS.domain.Entities.Event_Code", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<string>("Date_Created")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Event_Codes");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Code = "W",
                            Date_Created = "2025-02-21T23:10:51.3047621+00:00",
                            Description = "Railcar equipment is released from origin",
                            Name = "Released"
                        },
                        new
                        {
                            Id = -2,
                            Code = "A",
                            Date_Created = "2025-02-21T23:10:51.3047737+00:00",
                            Description = "Railcar equipment arrives at a city on route",
                            Name = "Arrived"
                        },
                        new
                        {
                            Id = -3,
                            Code = "D",
                            Date_Created = "2025-02-21T23:10:51.3047777+00:00",
                            Description = "Railcar equipment departs from a city on route",
                            Name = "Departed"
                        },
                        new
                        {
                            Id = -4,
                            Code = "Z",
                            Date_Created = "2025-02-21T23:10:51.3047811+00:00",
                            Description = "Railcar equipment is placed at destination",
                            Name = "Placed"
                        });
                });

            modelBuilder.Entity("TMS.domain.Entities.Trip", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Date_Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("Destination_CityId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Duration")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("End_Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("EquipmentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasIssue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Origin_CityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Start_Date")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Destination_CityId");

                    b.HasIndex("Origin_CityId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("TMS.domain.Entities.Event", b =>
                {
                    b.HasOne("TMS.domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TMS.domain.Entities.Trip", "Trip")
                        .WithMany("Events")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TMS.domain.Entities.Trip", b =>
                {
                    b.HasOne("TMS.domain.Entities.City", "Destination_City")
                        .WithMany("Destination_Cities")
                        .HasForeignKey("Destination_CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TMS.domain.Entities.City", "Origin_City")
                        .WithMany("Start_Cities")
                        .HasForeignKey("Origin_CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destination_City");

                    b.Navigation("Origin_City");
                });

            modelBuilder.Entity("TMS.domain.Entities.City", b =>
                {
                    b.Navigation("Destination_Cities");

                    b.Navigation("Start_Cities");
                });

            modelBuilder.Entity("TMS.domain.Entities.Trip", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
