// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMS.infra.Persistence.Context;

#nullable disable

namespace tms.infra.Migrations
{
    [DbContext(typeof(dbContext))]
    partial class dbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("TMS.domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date_Created")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date_Created = "2025-02-20T23:37:20.1536946+00:00",
                            Name = "Vancouver",
                            TimeZone = "Pacific Standard Time"
                        },
                        new
                        {
                            Id = 2,
                            Date_Created = "2025-02-20T23:37:20.1537248+00:00",
                            Name = "Victoria",
                            TimeZone = "Pacific Standard Time"
                        },
                        new
                        {
                            Id = 3,
                            Date_Created = "2025-02-20T23:37:20.1537310+00:00",
                            Name = "Kelowna",
                            TimeZone = "Pacific Standard Time"
                        },
                        new
                        {
                            Id = 4,
                            Date_Created = "2025-02-20T23:37:20.1537366+00:00",
                            Name = "Kamloops",
                            TimeZone = "Pacific Standard Time"
                        },
                        new
                        {
                            Id = 5,
                            Date_Created = "2025-02-20T23:37:20.1537424+00:00",
                            Name = "Prince George",
                            TimeZone = "Pacific Standard Time"
                        },
                        new
                        {
                            Id = 6,
                            Date_Created = "2025-02-20T23:37:20.1537487+00:00",
                            Name = "Calgary",
                            TimeZone = "Mountain Standard Time"
                        },
                        new
                        {
                            Id = 7,
                            Date_Created = "2025-02-20T23:37:20.1537542+00:00",
                            Name = "Edmonton",
                            TimeZone = "Mountain Standard Time"
                        },
                        new
                        {
                            Id = 8,
                            Date_Created = "2025-02-20T23:37:20.1537598+00:00",
                            Name = "Lethbridge",
                            TimeZone = "Mountain Standard Time"
                        },
                        new
                        {
                            Id = 9,
                            Date_Created = "2025-02-20T23:37:20.1537651+00:00",
                            Name = "Red Deer",
                            TimeZone = "Mountain Standard Time"
                        },
                        new
                        {
                            Id = 10,
                            Date_Created = "2025-02-20T23:37:20.1537715+00:00",
                            Name = "Fort McMurray",
                            TimeZone = "Mountain Standard Time"
                        },
                        new
                        {
                            Id = 11,
                            Date_Created = "2025-02-20T23:37:20.1537990+00:00",
                            Name = "Regina",
                            TimeZone = "Canada Central Standard Time"
                        },
                        new
                        {
                            Id = 12,
                            Date_Created = "2025-02-20T23:37:20.1538056+00:00",
                            Name = "Saskatoon",
                            TimeZone = "Canada Central Standard Time"
                        },
                        new
                        {
                            Id = 13,
                            Date_Created = "2025-02-20T23:37:20.1538119+00:00",
                            Name = "Moose Jaw",
                            TimeZone = "Canada Central Standard Time"
                        },
                        new
                        {
                            Id = 14,
                            Date_Created = "2025-02-20T23:37:20.1538172+00:00",
                            Name = "Brandon",
                            TimeZone = "Central Standard Time"
                        },
                        new
                        {
                            Id = 15,
                            Date_Created = "2025-02-20T23:37:20.1538225+00:00",
                            Name = "Winnipeg",
                            TimeZone = "Central Standard Time"
                        },
                        new
                        {
                            Id = 16,
                            Date_Created = "2025-02-20T23:37:20.1538284+00:00",
                            Name = "Thunder Bay",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 17,
                            Date_Created = "2025-02-20T23:37:20.1538343+00:00",
                            Name = "Sault Ste. Marie",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 18,
                            Date_Created = "2025-02-20T23:37:20.1538404+00:00",
                            Name = "Sudbury",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 19,
                            Date_Created = "2025-02-20T23:37:20.1538455+00:00",
                            Name = "North Bay",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 20,
                            Date_Created = "2025-02-20T23:37:20.1538507+00:00",
                            Name = "Barrie",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 21,
                            Date_Created = "2025-02-20T23:37:20.1538557+00:00",
                            Name = "Toronto",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 22,
                            Date_Created = "2025-02-20T23:37:20.1538613+00:00",
                            Name = "Mississauga",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 23,
                            Date_Created = "2025-02-20T23:37:20.1538668+00:00",
                            Name = "Hamilton",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 24,
                            Date_Created = "2025-02-20T23:37:20.1538717+00:00",
                            Name = "London",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 25,
                            Date_Created = "2025-02-20T23:37:20.1538772+00:00",
                            Name = "Kitchener",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 26,
                            Date_Created = "2025-02-20T23:37:20.1538824+00:00",
                            Name = "Windsor",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 27,
                            Date_Created = "2025-02-20T23:37:20.1538886+00:00",
                            Name = "St. Catharines",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 28,
                            Date_Created = "2025-02-20T23:37:20.1538937+00:00",
                            Name = "Oshawa",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 29,
                            Date_Created = "2025-02-20T23:37:20.1538989+00:00",
                            Name = "Kingston",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 30,
                            Date_Created = "2025-02-20T23:37:20.1539041+00:00",
                            Name = "Ottawa",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 31,
                            Date_Created = "2025-02-20T23:37:20.1539200+00:00",
                            Name = "Gatineau",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 32,
                            Date_Created = "2025-02-20T23:37:20.1539260+00:00",
                            Name = "Montreal",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 33,
                            Date_Created = "2025-02-20T23:37:20.1539317+00:00",
                            Name = "Quebec City",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 34,
                            Date_Created = "2025-02-20T23:37:20.1539381+00:00",
                            Name = "Sherbrooke",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 35,
                            Date_Created = "2025-02-20T23:37:20.1539439+00:00",
                            Name = "Trois-Rivières",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 36,
                            Date_Created = "2025-02-20T23:37:20.1539494+00:00",
                            Name = "Saguenay",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 37,
                            Date_Created = "2025-02-20T23:37:20.1539550+00:00",
                            Name = "Rimouski",
                            TimeZone = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 38,
                            Date_Created = "2025-02-20T23:37:20.1539607+00:00",
                            Name = "Edmundston",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 39,
                            Date_Created = "2025-02-20T23:37:20.1539664+00:00",
                            Name = "Fredericton",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 40,
                            Date_Created = "2025-02-20T23:37:20.1539711+00:00",
                            Name = "Moncton",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 41,
                            Date_Created = "2025-02-20T23:37:20.1539767+00:00",
                            Name = "Saint John",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 42,
                            Date_Created = "2025-02-20T23:37:20.1539823+00:00",
                            Name = "Bathurst",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 43,
                            Date_Created = "2025-02-20T23:37:20.1539884+00:00",
                            Name = "Charlottetown",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 44,
                            Date_Created = "2025-02-20T23:37:20.1539941+00:00",
                            Name = "Summerside",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 45,
                            Date_Created = "2025-02-20T23:37:20.1539996+00:00",
                            Name = "Sydney",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 46,
                            Date_Created = "2025-02-20T23:37:20.1540048+00:00",
                            Name = "Truro",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 47,
                            Date_Created = "2025-02-20T23:37:20.1540101+00:00",
                            Name = "New Glasgow",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 48,
                            Date_Created = "2025-02-20T23:37:20.1540156+00:00",
                            Name = "Dartmouth",
                            TimeZone = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 49,
                            Date_Created = "2025-02-20T23:37:20.1540208+00:00",
                            Name = "Halifax",
                            TimeZone = "Atlantic Standard Time"
                        });
                });

            modelBuilder.Entity("TMS.domain.Entities.Event_Code", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<string>("Date_Created")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Event_Codes");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Code = "W",
                            Date_Created = "2025-02-20T23:37:20.1493448+00:00",
                            Description = "Railcar equipment is released from origin",
                            Name = "Released"
                        },
                        new
                        {
                            Id = -2,
                            Code = "A",
                            Date_Created = "2025-02-20T23:37:20.1493709+00:00",
                            Description = "Railcar equipment arrives at a city on route",
                            Name = "Arrived"
                        },
                        new
                        {
                            Id = -3,
                            Code = "D",
                            Date_Created = "2025-02-20T23:37:20.1493786+00:00",
                            Description = "Railcar equipment departs from a city on route",
                            Name = "Departed"
                        },
                        new
                        {
                            Id = -4,
                            Code = "Z",
                            Date_Created = "2025-02-20T23:37:20.1493846+00:00",
                            Description = "Railcar equipment is placed at destination",
                            Name = "Placed"
                        });
                });

            modelBuilder.Entity("TMS.domain.Entities.Trip", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Date_Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("Destination_CityId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Duration")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("CAST((julianday(End_Date || ' UTC') - julianday(Start_Date || ' UTC')) * 24 * 60 AS INTEGER)", true);

                    b.Property<DateTimeOffset>("End_Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("EquipmentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasIssue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Origin_CityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Start_Date")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Destination_CityId");

                    b.HasIndex("Origin_CityId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("TMS.domain.Entities.Trip", b =>
                {
                    b.HasOne("TMS.domain.Entities.City", "Destination_City")
                        .WithMany("Destination_Cities")
                        .HasForeignKey("Destination_CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TMS.domain.Entities.City", "Origin_City")
                        .WithMany("Start_Cities")
                        .HasForeignKey("Origin_CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destination_City");

                    b.Navigation("Origin_City");
                });

            modelBuilder.Entity("TMS.domain.Entities.City", b =>
                {
                    b.Navigation("Destination_Cities");

                    b.Navigation("Start_Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
